-- UniVault Database Cleanup Script
-- Use this to reset the database to a clean state
-- Version: 1.0
-- Last Updated: 2025-06-24

USE univault_schema;

-- Temporarily disable foreign key checks to allow truncation
SET FOREIGN_KEY_CHECKS = 0;

-- Truncate data from main tables (dependent tables first)
TRUNCATE TABLE REVIEW_QUEUE;
TRUNCATE TABLE CUSTOMER_ACCOUNT;
TRUNCATE TABLE ALIAS_DOCUMENTATION;
TRUNCATE TABLE CUSTOMER_WORK_NATURE;
TRUNCATE TABLE CUSTOMER_FUND_SOURCE;
TRUNCATE TABLE CUSTOMER_ID;
TRUNCATE TABLE CUSTOMER_CONTACT_DETAILS;
TRUNCATE TABLE CUSTOMER_ADDRESS;
TRUNCATE TABLE CUSTOMER_ALIAS;
TRUNCATE TABLE CUSTOMER_EMPLOYMENT_INFORMATION;
TRUNCATE TABLE ACCOUNT_DETAILS;
TRUNCATE TABLE CUSTOMER;
TRUNCATE TABLE BANK_EMPLOYEE;

-- Truncate data from reference tables
TRUNCATE TABLE ID_TYPE;
TRUNCATE TABLE ALIAS_DOCUMENTATION_TYPE;
TRUNCATE TABLE CUSTOMER_PRODUCT_TYPE;
-- BIOMETRIC_TYPE table removed from schema
TRUNCATE TABLE WORK_NATURE_TYPE;
TRUNCATE TABLE FUND_SOURCE_TYPE;
TRUNCATE TABLE EMPLOYMENT_POSITION;
TRUNCATE TABLE CONTACT_TYPE;
TRUNCATE TABLE ADDRESS_TYPE;
TRUNCATE TABLE CIVIL_STATUS_TYPE;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;
