services:
  - type: web
    name: univault-app
    env: node
    buildCommand: cd 2_backend && npm install
    startCommand: cd 2_backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: univault-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: univault-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: univault-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: univault-db
          property: database
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: univault-db
    databaseName: univault_schema
    user: univault_user
    plan: starter
